2023-12-27 23:32:34,621 - ERROR - exception.py - handler_err - 46 - An error occurred: auth.logout
